export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS';
export const LOAD_TASKS_REQUESTED = 'LOAD_TASKS_REQUESTED';
export const LOAD_TASKS_ERROR = 'LOAD_TASKS_ERROR';
export const MOVE_CARD = 'MOVE_CARD';
export const SET_CURRENT_VIEW = 'SET_CURRENT_VIEW';
